import type { HelpContent, HelpLocale } from "./types";

/**
 * PM-CONV-04, Track B (origem) — conteúdo real de ajuda por rota × idioma.
 * Lacuna de PT-PT/ES/FR fechada em PM-CONV-06, Track D.
 *
 * Cobertura atual (declarada explicitamente, §28 do comando original —
 * "separar novo conteúdo coberto de legado ainda pendente"):
 * - PT-BR: todas as 24 rotas registradas em `registry.ts`.
 * - EN: todas as 24 rotas registradas.
 * - PT-PT / ES / FR: todas as 24 rotas registradas — PM-CONV-06 completou as
 *   17 rotas que, ao final de PM-CONV-04/05, tinham apenas PT-BR e EN
 *   (dashboard.overview, leads.detail, inbox.overview, canais.whatsapp,
 *   gates.overview, custos.overview, politica.overview, documentos.overview,
 *   viagens.detail, profissionais.overview, fornecedores.overview,
 *   veiculos.overview, jobs.overview, auth.login, auth.trocarSenha,
 *   auth.selecionarEmpresa, ouvidoria.detail), somando-se às 7 rotas que já
 *   tinham os 5 idiomas (leads.list, viagens.list, checkin.overview,
 *   parceiros.overview, premiacoes.overview, ouvidoria.list,
 *   operacoes.overview). Conteúdo em PT-PT/ES/FR é tradução própria (não
 *   cópia do PT-BR/EN com a chave de idioma trocada) — verificado por
 *   `tests/unit/help.test.ts`, que assevera `localesComConteudoProprio`
 *   com os 5 `HELP_LOCALES` para toda entrada de `HELP_ROUTES`.
 *
 *   O mecanismo de fallback (ver `../help/index.ts`) continua existindo e
 *   testado (pt-PT sem conteúdo próprio cai em pt-BR, depois EN, depois
 *   PT-BR padrão — nunca mostra a chave crua ao usuário), mas com esta
 *   rodada ele deixa de ser necessário para cobrir nenhuma rota × idioma
 *   registrado: é rede de segurança para o futuro, não mais uma lacuna
 *   conhecida do presente.
 */
export const HELP_CONTENT: Record<string, Partial<Record<HelpLocale, HelpContent>>> = {
  "dashboard.overview": {
    "pt-BR": {
      titulo: "Painel",
      objetivo: "Visão geral rápida do funil comercial: quantos leads existem, quantos estão em aberto e quantos contatos já foram cadastrados.",
      quemUsa: "Qualquer pessoa com acesso ao sistema, geralmente a primeira tela do dia.",
      campos: "Leads no funil, Leads em aberto, Contatos cadastrados — três números, sem filtro.",
      acoes: "Nenhuma ação aqui — é só leitura. Para agir, use o menu Leads.",
    },
    en: {
      titulo: "Dashboard",
      objetivo: "Quick overview of the sales funnel: how many leads exist, how many are open, and how many contacts are registered.",
      quemUsa: "Anyone with access to the system — usually the first screen of the day.",
      campos: "Leads in funnel, Open leads, Registered contacts — three numbers, no filter.",
      acoes: "No actions here — read-only. Use the Leads menu to act.",
    },
    "pt-PT": {
      titulo: "Painel",
      objetivo: "Visão geral rápida do funil comercial: quantos leads existem, quantos estão em aberto e quantos contactos já foram registados.",
      quemUsa: "Qualquer pessoa com acesso ao sistema, normalmente o primeiro ecrã do dia.",
      campos: "Leads no funil, Leads em aberto, Contactos registados — três números, sem filtro.",
      acoes: "Nenhuma ação aqui — é apenas leitura. Para agir, utilize o menu Leads.",
    },
    es: {
      titulo: "Panel",
      objetivo: "Vista general rápida del embudo comercial: cuántos leads existen, cuántos están abiertos y cuántos contactos ya se han registrado.",
      quemUsa: "Cualquier persona con acceso al sistema, normalmente la primera pantalla del día.",
      campos: "Leads en el embudo, Leads abiertos, Contactos registrados — tres números, sin filtro.",
      acoes: "Ninguna acción aquí — es solo lectura. Para actuar, use el menú Leads.",
    },
    fr: {
      titulo: "Tableau de bord",
      objetivo: "Vue d'ensemble rapide de l'entonnoir commercial : combien de prospects existent, combien sont ouverts et combien de contacts sont déjà enregistrés.",
      quemUsa: "Toute personne ayant accès au système, généralement le premier écran de la journée.",
      campos: "Prospects dans l'entonnoir, Prospects ouverts, Contacts enregistrés — trois chiffres, sans filtre.",
      acoes: "Aucune action ici — lecture seule. Pour agir, utilisez le menu Prospects.",
    },
  },
  "leads.list": {
    "pt-BR": {
      titulo: "Leads",
      objetivo: "Ver e organizar todos os leads do funil comercial, por etapa (Novo lead, Contato feito, Proposta enviada, Fechado, Perdido).",
      quemUsa: "Vendas e Atendimento no dia a dia; Administrador para supervisão.",
      campos: "Filtros por nome/telefone, responsável e origem. Formulário de criação: nome, telefone, origem, valor estimado, etapa inicial.",
      estados: "Um lead pertence a uma etapa do funil por vez — mover de etapa é uma ação explícita, nunca automática.",
      acoes: "Criar lead manualmente; filtrar a lista; clicar num lead para abrir o detalhe.",
      avisos: "Leads também chegam automaticamente pelo formulário público do site — nem todo lead nasce aqui.",
    },
    en: {
      titulo: "Leads",
      objetivo: "View and organize every lead in the sales funnel, by stage (New lead, Contacted, Proposal sent, Won, Lost).",
      quemUsa: "Sales and Support day-to-day; Administrator for oversight.",
      campos: "Filters by name/phone, owner and source. Creation form: name, phone, source, estimated value, starting stage.",
      estados: "A lead belongs to one funnel stage at a time — moving stages is always an explicit action, never automatic.",
      acoes: "Create a lead manually; filter the list; click a lead to open its detail page.",
      avisos: "Leads also arrive automatically from the public site form — not every lead is created here.",
    },
    "pt-PT": {
      titulo: "Leads",
      objetivo: "Ver e organizar todos os leads do funil comercial, por etapa (Novo lead, Contacto feito, Proposta enviada, Fechado, Perdido).",
      quemUsa: "Vendas e Atendimento no dia a dia; Administrador para supervisão.",
      campos: "Filtros por nome/telemóvel, responsável e origem. Formulário de criação: nome, telemóvel, origem, valor estimado, etapa inicial.",
      acoes: "Criar lead manualmente; filtrar a lista; clicar num lead para abrir o detalhe.",
    },
    es: {
      titulo: "Leads",
      objetivo: "Ver y organizar todos los leads del embudo comercial, por etapa (Nuevo lead, Contacto realizado, Propuesta enviada, Ganado, Perdido).",
      quemUsa: "Ventas y Atención al cliente en el día a día; Administrador para supervisión.",
      campos: "Filtros por nombre/teléfono, responsable y origen. Formulario de creación: nombre, teléfono, origen, valor estimado, etapa inicial.",
      acoes: "Crear lead manualmente; filtrar la lista; hacer clic en un lead para abrir el detalle.",
    },
    fr: {
      titulo: "Prospects",
      objetivo: "Voir et organiser tous les prospects de l'entonnoir commercial, par étape (Nouveau prospect, Contact effectué, Proposition envoyée, Gagné, Perdu).",
      quemUsa: "Ventes et Support au quotidien ; Administrateur pour la supervision.",
      campos: "Filtres par nom/téléphone, responsable et origine. Formulaire de création : nom, téléphone, origine, valeur estimée, étape initiale.",
      acoes: "Créer un prospect manuellement ; filtrer la liste ; cliquer sur un prospect pour ouvrir le détail.",
    },
  },
  "leads.detail": {
    "pt-BR": {
      titulo: "Detalhe do lead",
      objetivo: "Central de tudo sobre um cliente: score, próxima ação sugerida, propostas, reservas, pagamentos, comissões, documentos, viagem vinculada e histórico.",
      quemUsa: "Vendas e Atendimento.",
      campos: "Dados de contato, preferências de viagem, propostas comerciais, reserva (quando existe), passageiros, pagamentos, comissões, documentos, notas e tarefas.",
      estados: "O status do lead (ABERTO/etc.) é distinto do status da Proposta e do Booking — são três máquinas de estados diferentes que aparecem juntas nesta tela.",
      acoes: "Mudar etapa do funil, criar proposta, aceitar/recusar proposta, criar reserva, adicionar passageiro, registrar pagamento, vincular a uma viagem.",
      avisos: "Ações financeiras sensíveis (estorno, pagamento de comissão) passam por aprovação (Gate) — não são instantâneas.",
    },
    en: {
      titulo: "Lead detail",
      objetivo: "Everything about one customer in one place: score, suggested next action, proposals, bookings, payments, commissions, documents, linked trip and history.",
      quemUsa: "Sales and Support.",
      campos: "Contact info, travel preferences, commercial proposals, booking (when it exists), passengers, payments, commissions, documents, notes and tasks.",
      estados: "The lead's status is distinct from the Proposal's and the Booking's — three different state machines shown together on this page.",
      acoes: "Move funnel stage, create a proposal, accept/decline a proposal, create a booking, add a passenger, record a payment, link to a trip.",
      avisos: "Sensitive financial actions (refunds, commission payouts) go through approval (a Gate) — they are never instant.",
    },
    "pt-PT": {
      titulo: "Detalhe do lead",
      objetivo: "Central de tudo sobre um cliente: pontuação, próxima ação sugerida, propostas, reservas, pagamentos, comissões, documentos, viagem associada e histórico.",
      quemUsa: "Vendas e Atendimento.",
      campos: "Dados de contacto, preferências de viagem, propostas comerciais, reserva (quando existe), passageiros, pagamentos, comissões, documentos, notas e tarefas.",
      estados: "O estado do lead (ABERTO/etc.) é distinto do estado da Proposta e do Booking — são três máquinas de estados diferentes que aparecem juntas neste ecrã.",
      acoes: "Mudar de etapa no funil, criar proposta, aceitar/recusar proposta, criar reserva, adicionar passageiro, registar pagamento, associar a uma viagem.",
      avisos: "Ações financeiras sensíveis (estorno, pagamento de comissão) passam por aprovação (Gate) — nunca são instantâneas.",
    },
    es: {
      titulo: "Detalle del lead",
      objetivo: "Centro de todo sobre un cliente: puntuación, próxima acción sugerida, propuestas, reservas, pagos, comisiones, documentos, viaje vinculado e historial.",
      quemUsa: "Ventas y Atención al cliente.",
      campos: "Datos de contacto, preferencias de viaje, propuestas comerciales, reserva (cuando existe), pasajeros, pagos, comisiones, documentos, notas y tareas.",
      estados: "El estado del lead (ABIERTO/etc.) es distinto del estado de la Propuesta y del Booking — son tres máquinas de estados diferentes que aparecen juntas en esta pantalla.",
      acoes: "Cambiar de etapa en el embudo, crear propuesta, aceptar/rechazar propuesta, crear reserva, añadir pasajero, registrar pago, vincular a un viaje.",
      avisos: "Las acciones financieras sensibles (reembolso, pago de comisión) pasan por aprobación (Gate) — nunca son instantáneas.",
    },
    fr: {
      titulo: "Détail du prospect",
      objetivo: "Toutes les informations sur un client en un seul endroit : score, prochaine action suggérée, propositions, réservations, paiements, commissions, documents, voyage lié et historique.",
      quemUsa: "Ventes et Support.",
      campos: "Coordonnées, préférences de voyage, propositions commerciales, réservation (le cas échéant), passagers, paiements, commissions, documents, notes et tâches.",
      estados: "Le statut du prospect (OUVERT/etc.) est distinct du statut de la Proposition et du Booking — trois machines à états différentes apparaissent ensemble sur cet écran.",
      acoes: "Changer d'étape dans l'entonnoir, créer une proposition, accepter/refuser une proposition, créer une réservation, ajouter un passager, enregistrer un paiement, lier à un voyage.",
      avisos: "Les actions financières sensibles (remboursement, versement de commission) passent par une approbation (Gate) — elles ne sont jamais instantanées.",
    },
  },
  "inbox.overview": {
    "pt-BR": {
      titulo: "Inbox",
      objetivo: "Atender conversas de qualquer canal (hoje: WhatsApp) em um só lugar.",
      quemUsa: "Atendimento.",
      campos: "Lista de conversas por contato; histórico de mensagens da conversa selecionada.",
      acoes: "Responder manualmente quando o canal é WhatsApp e você tem permissão de atendimento.",
      avisos: "As mensagens aparecem exatamente como chegaram — nenhuma tradução ou processamento automático é aplicado.",
    },
    en: {
      titulo: "Inbox",
      objetivo: "Handle conversations from any channel (currently: WhatsApp) in one place.",
      quemUsa: "Support.",
      campos: "List of conversations by contact; message history for the selected conversation.",
      acoes: "Reply manually when the channel is WhatsApp and you have support permission.",
      avisos: "Messages appear exactly as received — no automatic translation or processing is applied.",
    },
    "pt-PT": {
      titulo: "Caixa de entrada",
      objetivo: "Atender conversas de qualquer canal (atualmente: WhatsApp) num só lugar.",
      quemUsa: "Atendimento.",
      campos: "Lista de conversas por contacto; histórico de mensagens da conversa selecionada.",
      acoes: "Responder manualmente quando o canal é o WhatsApp e tiver permissão de atendimento.",
      avisos: "As mensagens aparecem exatamente como chegaram — não é aplicada qualquer tradução ou processamento automático.",
    },
    es: {
      titulo: "Bandeja de entrada",
      objetivo: "Atender conversaciones de cualquier canal (hoy: WhatsApp) en un solo lugar.",
      quemUsa: "Atención al cliente.",
      campos: "Lista de conversaciones por contacto; historial de mensajes de la conversación seleccionada.",
      acoes: "Responder manualmente cuando el canal es WhatsApp y tiene permiso de atención al cliente.",
      avisos: "Los mensajes aparecen exactamente como llegaron — no se aplica ninguna traducción ni procesamiento automático.",
    },
    fr: {
      titulo: "Boîte de réception",
      objetivo: "Gérer les conversations de n'importe quel canal (aujourd'hui : WhatsApp) en un seul endroit.",
      quemUsa: "Support.",
      campos: "Liste des conversations par contact ; historique des messages de la conversation sélectionnée.",
      acoes: "Répondre manuellement lorsque le canal est WhatsApp et que vous avez l'autorisation de support.",
      avisos: "Les messages apparaissent exactement comme ils sont arrivés — aucune traduction ni traitement automatique n'est appliqué.",
    },
  },
  "canais.whatsapp": {
    "pt-BR": {
      titulo: "Canais",
      objetivo: "Configurar a conta do WhatsApp Cloud API usada pelo tenant.",
      quemUsa: "Administrador.",
      campos: "Credenciais da conta WhatsApp Business (armazenadas de forma segura, nunca em texto plano).",
      avisos: "Esta tela contém segredos — só quem tem whatsapp.manage pode ver/editar.",
    },
    en: {
      titulo: "Channels",
      objetivo: "Configure the WhatsApp Cloud API account used by the tenant.",
      quemUsa: "Administrator.",
      campos: "WhatsApp Business account credentials (stored securely, never in plain text).",
      avisos: "This screen contains secrets — only users with whatsapp.manage can view/edit it.",
    },
    "pt-PT": {
      titulo: "Canais",
      objetivo: "Configurar a conta do WhatsApp Cloud API utilizada pelo tenant.",
      quemUsa: "Administrador.",
      campos: "Credenciais da conta WhatsApp Business (armazenadas de forma segura, nunca em texto simples).",
      avisos: "Este ecrã contém segredos — só quem tem whatsapp.manage pode ver/editar.",
    },
    es: {
      titulo: "Canales",
      objetivo: "Configurar la cuenta de WhatsApp Cloud API utilizada por el tenant.",
      quemUsa: "Administrador.",
      campos: "Credenciales de la cuenta de WhatsApp Business (almacenadas de forma segura, nunca en texto plano).",
      avisos: "Esta pantalla contiene secretos — solo quien tiene whatsapp.manage puede verlos/editarlos.",
    },
    fr: {
      titulo: "Canaux",
      objetivo: "Configurer le compte WhatsApp Cloud API utilisé par le tenant.",
      quemUsa: "Administrateur.",
      campos: "Identifiants du compte WhatsApp Business (stockés de manière sécurisée, jamais en texte clair).",
      avisos: "Cet écran contient des secrets — seules les personnes disposant de whatsapp.manage peuvent les consulter/modifier.",
    },
  },
  "gates.overview": {
    "pt-BR": {
      titulo: "Aprovações (Gates)",
      objetivo: "Decidir pedidos de aprovação para ações sensíveis (estorno, pagamento de comissão, etc.) antes que elas sejam executadas.",
      quemUsa: "Quem tem gates.decide — normalmente Administrador.",
      estados: "PENDENTE → APROVADO/REJEITADO/MODIFICADO, ou EXPIRADO se ninguém decidir a tempo (24h por padrão).",
      acoes: "Aprovar, rejeitar ou modificar um pedido pendente.",
      avisos: "Um Gate já decidido nunca muda de novo — se o dado subjacente mudar depois da aprovação, o sistema pode recusar a execução (fingerprint).",
    },
    en: {
      titulo: "Approvals (Gates)",
      objetivo: "Decide approval requests for sensitive actions (refunds, commission payouts, etc.) before they execute.",
      quemUsa: "Whoever has gates.decide — usually the Administrator.",
      estados: "PENDING → APPROVED/REJECTED/MODIFIED, or EXPIRED if nobody decides in time (24h by default).",
      acoes: "Approve, reject or modify a pending request.",
      avisos: "A decided Gate never changes again — if the underlying data changes after approval, the system may refuse to execute it (fingerprint check).",
    },
    "pt-PT": {
      titulo: "Aprovações (Gates)",
      objetivo: "Decidir pedidos de aprovação para ações sensíveis (estorno, pagamento de comissão, etc.) antes de serem executadas.",
      quemUsa: "Quem tem gates.decide — normalmente o Administrador.",
      estados: "PENDENTE → APROVADO/REJEITADO/MODIFICADO, ou EXPIRADO se ninguém decidir a tempo (24h por defeito).",
      acoes: "Aprovar, rejeitar ou modificar um pedido pendente.",
      avisos: "Um Gate já decidido nunca volta a mudar — se o dado subjacente mudar depois da aprovação, o sistema pode recusar a execução (fingerprint).",
    },
    es: {
      titulo: "Aprobaciones (Gates)",
      objetivo: "Decidir solicitudes de aprobación para acciones sensibles (reembolso, pago de comisión, etc.) antes de que se ejecuten.",
      quemUsa: "Quien tiene gates.decide — normalmente el Administrador.",
      estados: "PENDIENTE → APROBADO/RECHAZADO/MODIFICADO, o EXPIRADO si nadie decide a tiempo (24h por defecto).",
      acoes: "Aprobar, rechazar o modificar una solicitud pendiente.",
      avisos: "Un Gate ya decidido nunca vuelve a cambiar — si el dato subyacente cambia después de la aprobación, el sistema puede rechazar la ejecución (fingerprint).",
    },
    fr: {
      titulo: "Approbations (Gates)",
      objetivo: "Décider des demandes d'approbation pour des actions sensibles (remboursement, versement de commission, etc.) avant leur exécution.",
      quemUsa: "Quiconque a gates.decide — généralement l'Administrateur.",
      estados: "EN_ATTENTE → APPROUVÉ/REJETÉ/MODIFIÉ, ou EXPIRÉ si personne ne décide à temps (24h par défaut).",
      acoes: "Approuver, rejeter ou modifier une demande en attente.",
      avisos: "Un Gate déjà décidé ne change plus jamais — si la donnée sous-jacente change après l'approbation, le système peut refuser l'exécution (empreinte/fingerprint).",
    },
  },
  "custos.overview": {
    "pt-BR": {
      titulo: "Custos",
      objetivo: "Acompanhar consumo, políticas e limites de custo técnico/IA do tenant.",
      quemUsa: "Administrador.",
      acoes: "Configurar políticas e limites (quando tiver cost.manage).",
    },
    en: {
      titulo: "Costs",
      objetivo: "Track technical/AI cost usage, policies and limits for the tenant.",
      quemUsa: "Administrator.",
      acoes: "Configure policies and limits (with cost.manage).",
    },
    "pt-PT": {
      titulo: "Custos",
      objetivo: "Acompanhar o consumo, as políticas e os limites de custo técnico/IA do tenant.",
      quemUsa: "Administrador.",
      acoes: "Configurar políticas e limites (quando possuir cost.manage).",
    },
    es: {
      titulo: "Costos",
      objetivo: "Seguir el consumo, las políticas y los límites de costo técnico/IA del tenant.",
      quemUsa: "Administrador.",
      acoes: "Configurar políticas y límites (con cost.manage).",
    },
    fr: {
      titulo: "Coûts",
      objetivo: "Suivre la consommation, les politiques et les limites de coût technique/IA du tenant.",
      quemUsa: "Administrateur.",
      acoes: "Configurer les politiques et les limites (avec cost.manage).",
    },
  },
  "politica.overview": {
    "pt-BR": {
      titulo: "Política comercial",
      objetivo: "Configurar os limiares de desconto/margem/mudança de preço que exigem aprovação ao enviar uma proposta.",
      quemUsa: "Administrador.",
      campos: "Limite de desconto relevante, limite de mudança de preço excepcional, limite de margem mínima.",
      avisos: "Tenants que nunca configuram usam os mesmos valores padrão de antes (15%/20%/10%) — nada muda sozinho.",
    },
    en: {
      titulo: "Commercial policy",
      objetivo: "Configure the discount/margin/price-change thresholds that require approval when sending a proposal.",
      quemUsa: "Administrator.",
      campos: "Relevant discount threshold, exceptional price-change threshold, minimum margin threshold.",
      avisos: "Tenants that never configure this keep the same defaults as before (15%/20%/10%) — nothing changes on its own.",
    },
    "pt-PT": {
      titulo: "Política comercial",
      objetivo: "Configurar os limiares de desconto/margem/alteração de preço que exigem aprovação ao enviar uma proposta.",
      quemUsa: "Administrador.",
      campos: "Limite de desconto relevante, limite de alteração de preço excecional, limite de margem mínima.",
      avisos: "Tenants que nunca configuram usam os mesmos valores predefinidos de sempre (15%/20%/10%) — nada muda sozinho.",
    },
    es: {
      titulo: "Política comercial",
      objetivo: "Configurar los umbrales de descuento/margen/cambio de precio que requieren aprobación al enviar una propuesta.",
      quemUsa: "Administrador.",
      campos: "Umbral de descuento relevante, umbral de cambio de precio excepcional, umbral de margen mínimo.",
      avisos: "Los tenants que nunca configuran esto usan los mismos valores predeterminados de siempre (15%/20%/10%) — nada cambia solo.",
    },
    fr: {
      titulo: "Politique commerciale",
      objetivo: "Configurer les seuils de remise/marge/changement de prix qui exigent une approbation lors de l'envoi d'une proposition.",
      quemUsa: "Administrateur.",
      campos: "Seuil de remise significative, seuil de changement de prix exceptionnel, seuil de marge minimale.",
      avisos: "Les tenants qui ne configurent jamais cela gardent les mêmes valeurs par défaut qu'avant (15%/20%/10%) — rien ne change tout seul.",
    },
  },
  "documentos.overview": {
    "pt-BR": {
      titulo: "Documentos",
      objetivo: "Catálogo de requisitos documentais que todo passageiro precisa atender (ex.: \"Passaporte válido\").",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Nome, descrição, se é obrigatório.",
      acoes: "Criar requisito; desativar (nunca apaga o histórico de quem já enviou algo).",
      avisos: "Upload real de arquivo ainda não existe nesta versão — só o status (pendente/enviado/aprovado/etc.) é rastreado.",
    },
    en: {
      titulo: "Documents",
      objetivo: "Catalog of document requirements every passenger must meet (e.g. \"Valid passport\").",
      quemUsa: "Sales, Support, Administrator.",
      campos: "Name, description, whether it's mandatory.",
      acoes: "Create a requirement; deactivate it (never deletes the history of who already submitted something).",
      avisos: "Real file upload does not exist yet in this version — only the status (pending/submitted/approved/etc.) is tracked.",
    },
    "pt-PT": {
      titulo: "Documentos",
      objetivo: "Catálogo de requisitos documentais que todo o passageiro precisa de cumprir (ex.: \"Passaporte válido\").",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Nome, descrição, se é obrigatório.",
      acoes: "Criar requisito; desativar (nunca apaga o histórico de quem já submeteu algo).",
      avisos: "O envio real de ficheiros ainda não existe nesta versão — só o estado (pendente/enviado/aprovado/etc.) é registado.",
    },
    es: {
      titulo: "Documentos",
      objetivo: "Catálogo de requisitos documentales que todo pasajero debe cumplir (ej.: \"Pasaporte válido\").",
      quemUsa: "Ventas, Atención al cliente, Administrador.",
      campos: "Nombre, descripción, si es obligatorio.",
      acoes: "Crear requisito; desactivar (nunca borra el historial de quien ya envió algo).",
      avisos: "La carga real de archivos aún no existe en esta versión — solo se rastrea el estado (pendiente/enviado/aprobado/etc.).",
    },
    fr: {
      titulo: "Documents",
      objetivo: "Catalogue des exigences documentaires que chaque passager doit satisfaire (ex. : « Passeport valide »).",
      quemUsa: "Ventes, Support, Administrateur.",
      campos: "Nom, description, si c'est obligatoire.",
      acoes: "Créer une exigence ; désactiver (ne supprime jamais l'historique de qui a déjà envoyé quelque chose).",
      avisos: "Le téléversement réel de fichiers n'existe pas encore dans cette version — seul le statut (en attente/envoyé/approuvé/etc.) est suivi.",
    },
  },
  "viagens.list": {
    "pt-BR": {
      titulo: "Viagens",
      objetivo: "Ver e criar Trips — a execução operacional de uma partida, distinta da reserva comercial (Booking).",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Roteiro, mercado, datas de início/fim, timezone.",
      acoes: "Criar uma viagem; clicar para abrir o detalhe operacional completo.",
      avisos: "Uma Trip pode reunir várias reservas da mesma partida — não é 1 reserva = 1 viagem.",
    },
    en: {
      titulo: "Trips",
      objetivo: "View and create Trips — the operational execution of a departure, distinct from the commercial booking.",
      quemUsa: "Sales, Support, Administrator.",
      campos: "Itinerary name, market, start/end dates, timezone.",
      acoes: "Create a trip; click to open the full operational detail.",
      avisos: "One Trip can gather several bookings from the same departure — it's never 1 booking = 1 trip.",
    },
    "pt-PT": {
      titulo: "Viagens",
      objetivo: "Ver e criar Trips — a execução operacional de uma partida, distinta da reserva comercial (Booking).",
      quemUsa: "Vendas, Atendimento, Administrador.",
      acoes: "Criar uma viagem; clicar para abrir o detalhe operacional completo.",
    },
    es: {
      titulo: "Viajes",
      objetivo: "Ver y crear Trips — la ejecución operativa de una salida, distinta de la reserva comercial (Booking).",
      quemUsa: "Ventas, Atención al cliente, Administrador.",
      acoes: "Crear un viaje; hacer clic para abrir el detalle operativo completo.",
    },
    fr: {
      titulo: "Voyages",
      objetivo: "Voir et créer des Trips — l'exécution opérationnelle d'un départ, distincte de la réservation commerciale (Booking).",
      quemUsa: "Ventes, Support, Administrateur.",
      acoes: "Créer un voyage ; cliquer pour ouvrir le détail opérationnel complet.",
    },
  },
  "viagens.detail": {
    "pt-BR": {
      titulo: "Detalhe da viagem",
      objetivo: "Gerenciar a execução operacional completa: status, reservas vinculadas, itinerário dia a dia, checklist, grupos operacionais (crew/veículo/passageiros) e progresso de parada.",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Status da viagem, itinerário (dias e atividades), checklist por categoria, grupos operacionais.",
      estados: "PLANEJAMENTO → CONFIRMADA → EM_ANDAMENTO → CONCLUIDA, com CANCELADA a partir de Planejamento/Confirmada.",
      acoes: "Mudar status; adicionar dia/atividade ao itinerário; criar grupo operacional; atribuir profissional/veículo; vincular reserva ao grupo; atualizar progresso de parada.",
    },
    en: {
      titulo: "Trip detail",
      objetivo: "Manage the full operational execution: status, linked bookings, day-by-day itinerary, checklist, operational groups (crew/vehicle/passengers) and stop progress.",
      quemUsa: "Sales, Support, Administrator.",
      campos: "Trip status, itinerary (days and activities), checklist by category, operational groups.",
      estados: "PLANNING → CONFIRMED → IN_PROGRESS → COMPLETED, with CANCELLED reachable from Planning/Confirmed.",
      acoes: "Change status; add a day/activity to the itinerary; create an operational group; assign staff/vehicle; link a booking to the group; update stop progress.",
    },
    "pt-PT": {
      titulo: "Detalhe da viagem",
      objetivo: "Gerir a execução operacional completa: estado, reservas associadas, itinerário dia a dia, checklist, grupos operacionais (equipa/veículo/passageiros) e progresso de paragem.",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Estado da viagem, itinerário (dias e atividades), checklist por categoria, grupos operacionais.",
      estados: "PLANEAMENTO → CONFIRMADA → EM_CURSO → CONCLUÍDA, com CANCELADA a partir de Planeamento/Confirmada.",
      acoes: "Mudar de estado; adicionar dia/atividade ao itinerário; criar grupo operacional; atribuir profissional/veículo; associar reserva ao grupo; atualizar o progresso da paragem.",
    },
    es: {
      titulo: "Detalle del viaje",
      objetivo: "Gestionar la ejecución operativa completa: estado, reservas vinculadas, itinerario día a día, checklist, grupos operativos (equipo/vehículo/pasajeros) y progreso de parada.",
      quemUsa: "Ventas, Atención al cliente, Administrador.",
      campos: "Estado del viaje, itinerario (días y actividades), checklist por categoría, grupos operativos.",
      estados: "PLANIFICACIÓN → CONFIRMADO → EN_CURSO → COMPLETADO, con CANCELADO a partir de Planificación/Confirmado.",
      acoes: "Cambiar el estado; añadir día/actividad al itinerario; crear grupo operativo; asignar profesional/vehículo; vincular reserva al grupo; actualizar el progreso de la parada.",
    },
    fr: {
      titulo: "Détail du voyage",
      objetivo: "Gérer l'exécution opérationnelle complète : statut, réservations liées, itinéraire jour par jour, checklist, groupes opérationnels (équipe/véhicule/passagers) et avancement des arrêts.",
      quemUsa: "Ventes, Support, Administrateur.",
      campos: "Statut du voyage, itinéraire (jours et activités), checklist par catégorie, groupes opérationnels.",
      estados: "PLANIFICATION → CONFIRMÉ → EN_COURS → TERMINÉ, avec ANNULÉ atteignable depuis Planification/Confirmé.",
      acoes: "Changer le statut ; ajouter un jour/une activité à l'itinéraire ; créer un groupe opérationnel ; affecter un professionnel/véhicule ; lier une réservation au groupe ; mettre à jour l'avancement de l'arrêt.",
    },
  },
  "profissionais.overview": {
    "pt-BR": {
      titulo: "Profissionais",
      objetivo: "Cadastro de guias e motoristas — uma pessoa, que pode acumular os dois papéis quando atribuída a um grupo operacional.",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Nome, telefone, e-mail, idiomas.",
      acoes: "Cadastrar; ativar/desativar.",
      avisos: "O papel (guia/motorista) não fica fixo no cadastro — é escolhido ao atribuir a pessoa a um grupo operacional específico.",
    },
    en: {
      titulo: "Staff",
      objetivo: "Registry of guides and drivers — one person, who can hold both roles when assigned to an operational group.",
      quemUsa: "Sales, Support, Administrator.",
      campos: "Name, phone, email, languages.",
      acoes: "Register; activate/deactivate.",
      avisos: "The role (guide/driver) isn't fixed on the record — it's chosen when assigning the person to a specific operational group.",
    },
    "pt-PT": {
      titulo: "Profissionais",
      objetivo: "Registo de guias e motoristas — uma pessoa, que pode acumular os dois papéis quando atribuída a um grupo operacional.",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Nome, telemóvel, e-mail, idiomas.",
      acoes: "Registar; ativar/desativar.",
      avisos: "O papel (guia/motorista) não fica fixo no registo — é escolhido ao atribuir a pessoa a um grupo operacional específico.",
    },
    es: {
      titulo: "Profesionales",
      objetivo: "Registro de guías y conductores — una persona, que puede acumular ambos roles cuando se le asigna a un grupo operativo.",
      quemUsa: "Ventas, Atención al cliente, Administrador.",
      campos: "Nombre, teléfono, correo electrónico, idiomas.",
      acoes: "Registrar; activar/desactivar.",
      avisos: "El rol (guía/conductor) no queda fijo en el registro — se elige al asignar la persona a un grupo operativo específico.",
    },
    fr: {
      titulo: "Professionnels",
      objetivo: "Registre des guides et chauffeurs — une même personne peut cumuler les deux rôles lorsqu'elle est affectée à un groupe opérationnel.",
      quemUsa: "Ventes, Support, Administrateur.",
      campos: "Nom, téléphone, e-mail, langues.",
      acoes: "Enregistrer ; activer/désactiver.",
      avisos: "Le rôle (guide/chauffeur) n'est pas fixé dans la fiche — il est choisi lors de l'affectation de la personne à un groupe opérationnel spécifique.",
    },
  },
  "fornecedores.overview": {
    "pt-BR": {
      titulo: "Fornecedores",
      objetivo: "Cadastro de hotéis, restaurantes, agências locais e demais parceiros operacionais.",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Nome, tipo, cidade, contato, e-mail.",
      acoes: "Cadastrar; ativar/desativar; referenciar numa atividade de itinerário.",
    },
    en: {
      titulo: "Suppliers",
      objetivo: "Registry of hotels, restaurants, local agencies and other operational partners.",
      quemUsa: "Sales, Support, Administrator.",
      campos: "Name, type, city, contact, email.",
      acoes: "Register; activate/deactivate; reference in an itinerary activity.",
    },
    "pt-PT": {
      titulo: "Fornecedores",
      objetivo: "Registo de hotéis, restaurantes, agências locais e demais parceiros operacionais.",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Nome, tipo, cidade, contacto, e-mail.",
      acoes: "Registar; ativar/desativar; referenciar numa atividade de itinerário.",
    },
    es: {
      titulo: "Proveedores",
      objetivo: "Registro de hoteles, restaurantes, agencias locales y demás socios operativos.",
      quemUsa: "Ventas, Atención al cliente, Administrador.",
      campos: "Nombre, tipo, ciudad, contacto, correo electrónico.",
      acoes: "Registrar; activar/desactivar; referenciar en una actividad del itinerario.",
    },
    fr: {
      titulo: "Fournisseurs",
      objetivo: "Registre des hôtels, restaurants, agences locales et autres partenaires opérationnels.",
      quemUsa: "Ventes, Support, Administrateur.",
      campos: "Nom, type, ville, contact, e-mail.",
      acoes: "Enregistrer ; activer/désactiver ; référencer dans une activité de l'itinéraire.",
    },
  },
  "veiculos.overview": {
    "pt-BR": {
      titulo: "Veículos",
      objetivo: "Cadastro de veículos de operação turística (van, ônibus, carro) — a capacidade limita quantos passageiros um grupo operacional comporta.",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Nome, capacidade, placa, categoria.",
      acoes: "Cadastrar; ativar/desativar.",
      avisos: "Não é o mesmo domínio de telemetria veicular (OBD2) — aqui é só um recurso de operação turística.",
    },
    en: {
      titulo: "Vehicles",
      objetivo: "Registry of tourism-operation vehicles (van, bus, car) — capacity limits how many passengers an operational group can hold.",
      quemUsa: "Sales, Support, Administrator.",
      campos: "Name, capacity, plate, category.",
      acoes: "Register; activate/deactivate.",
      avisos: "Not the same domain as vehicle telemetry (OBD2) — here it's purely a tourism-operation resource.",
    },
    "pt-PT": {
      titulo: "Veículos",
      objetivo: "Registo de veículos de operação turística (carrinha, autocarro, automóvel) — a capacidade limita quantos passageiros um grupo operacional comporta.",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Nome, capacidade, matrícula, categoria.",
      acoes: "Registar; ativar/desativar.",
      avisos: "Não é o mesmo domínio de telemetria de veículos (OBD2) — aqui é apenas um recurso de operação turística.",
    },
    es: {
      titulo: "Vehículos",
      objetivo: "Registro de vehículos de operación turística (furgoneta, autobús, coche) — la capacidad limita cuántos pasajeros admite un grupo operativo.",
      quemUsa: "Ventas, Atención al cliente, Administrador.",
      campos: "Nombre, capacidad, matrícula, categoría.",
      acoes: "Registrar; activar/desactivar.",
      avisos: "No es el mismo dominio de telemetría vehicular (OBD2) — aquí es solo un recurso de operación turística.",
    },
    fr: {
      titulo: "Véhicules",
      objetivo: "Registre des véhicules d'exploitation touristique (minibus, autocar, voiture) — la capacité limite le nombre de passagers qu'un groupe opérationnel peut accueillir.",
      quemUsa: "Ventes, Support, Administrateur.",
      campos: "Nom, capacité, plaque d'immatriculation, catégorie.",
      acoes: "Enregistrer ; activer/désactiver.",
      avisos: "Ce n'est pas le même domaine que la télémétrie des véhicules (OBD2) — ici, c'est uniquement une ressource d'exploitation touristique.",
    },
  },
  "jobs.overview": {
    "pt-BR": {
      titulo: "Jobs",
      objetivo: "Ver a fila de tarefas em segundo plano (envio de WhatsApp, verificação de pendências de documento, etc.).",
      quemUsa: "Quem tem jobs.view — normalmente Administrador.",
      estados: "READY → PROCESSING → SUCCEEDED, com RETRY_WAIT/DEAD_LETTER em falhas.",
      acoes: "Reenviar manualmente um job em dead-letter (com jobs.manage).",
    },
    en: {
      titulo: "Jobs",
      objetivo: "View the background task queue (WhatsApp sending, document pending checks, etc.).",
      quemUsa: "Whoever has jobs.view — usually the Administrator.",
      estados: "READY → PROCESSING → SUCCEEDED, with RETRY_WAIT/DEAD_LETTER on failures.",
      acoes: "Manually retry a dead-lettered job (with jobs.manage).",
    },
    "pt-PT": {
      titulo: "Jobs",
      objetivo: "Ver a fila de tarefas em segundo plano (envio de WhatsApp, verificação de pendências de documentos, etc.).",
      quemUsa: "Quem tem jobs.view — normalmente o Administrador.",
      estados: "READY → PROCESSING → SUCCEEDED, com RETRY_WAIT/DEAD_LETTER em caso de falha.",
      acoes: "Reenviar manualmente um job em dead-letter (com jobs.manage).",
    },
    es: {
      titulo: "Jobs",
      objetivo: "Ver la cola de tareas en segundo plano (envío de WhatsApp, verificación de documentos pendientes, etc.).",
      quemUsa: "Quien tiene jobs.view — normalmente el Administrador.",
      estados: "READY → PROCESSING → SUCCEEDED, con RETRY_WAIT/DEAD_LETTER en caso de fallos.",
      acoes: "Reenviar manualmente un job en dead-letter (con jobs.manage).",
    },
    fr: {
      titulo: "Tâches (Jobs)",
      objetivo: "Voir la file des tâches en arrière-plan (envoi WhatsApp, vérification des documents en attente, etc.).",
      quemUsa: "Quiconque a jobs.view — généralement l'Administrateur.",
      estados: "READY → PROCESSING → SUCCEEDED, avec RETRY_WAIT/DEAD_LETTER en cas d'échec.",
      acoes: "Relancer manuellement une tâche en dead-letter (avec jobs.manage).",
    },
  },
  "auth.login": {
    "pt-BR": { titulo: "Entrar", objetivo: "Autenticar com e-mail e senha para acessar o sistema.", quemUsa: "Qualquer usuário cadastrado.", campos: "E-mail, senha." },
    en: { titulo: "Sign in", objetivo: "Authenticate with email and password to access the system.", quemUsa: "Any registered user.", campos: "Email, password." },
    "pt-PT": { titulo: "Iniciar sessão", objetivo: "Autenticar-se com e-mail e palavra-passe para aceder ao sistema.", quemUsa: "Qualquer utilizador registado.", campos: "E-mail, palavra-passe." },
    es: { titulo: "Iniciar sesión", objetivo: "Autenticarse con correo electrónico y contraseña para acceder al sistema.", quemUsa: "Cualquier usuario registrado.", campos: "Correo electrónico, contraseña." },
    fr: { titulo: "Connexion", objetivo: "S'authentifier avec un e-mail et un mot de passe pour accéder au système.", quemUsa: "Tout utilisateur enregistré.", campos: "E-mail, mot de passe." },
  },
  "auth.trocarSenha": {
    "pt-BR": { titulo: "Trocar senha", objetivo: "Definir uma nova senha — obrigatório no primeiro acesso ou após um reset administrativo.", quemUsa: "Usuário recém-criado ou com senha resetada.", campos: "Senha atual, nova senha." },
    en: { titulo: "Change password", objetivo: "Set a new password — required on first access or after an administrative reset.", quemUsa: "A newly created user or one with a reset password.", campos: "Current password, new password." },
    "pt-PT": { titulo: "Alterar palavra-passe", objetivo: "Definir uma nova palavra-passe — obrigatório no primeiro acesso ou após uma reposição administrativa.", quemUsa: "Utilizador recém-criado ou com a palavra-passe reposta.", campos: "Palavra-passe atual, nova palavra-passe." },
    es: { titulo: "Cambiar contraseña", objetivo: "Definir una nueva contraseña — obligatorio en el primer acceso o después de un restablecimiento administrativo.", quemUsa: "Usuario recién creado o con contraseña restablecida.", campos: "Contraseña actual, nueva contraseña." },
    fr: { titulo: "Changer le mot de passe", objetivo: "Définir un nouveau mot de passe — obligatoire lors du premier accès ou après une réinitialisation administrative.", quemUsa: "Utilisateur nouvellement créé ou dont le mot de passe a été réinitialisé.", campos: "Mot de passe actuel, nouveau mot de passe." },
  },
  "auth.selecionarEmpresa": {
    "pt-BR": { titulo: "Selecionar empresa", objetivo: "Escolher qual tenant acessar, quando o usuário pertence a mais de um.", quemUsa: "Usuário com múltiplos vínculos (Membership)." },
    en: { titulo: "Select company", objetivo: "Choose which tenant to access, when the user belongs to more than one.", quemUsa: "A user with multiple memberships." },
    "pt-PT": { titulo: "Selecionar empresa", objetivo: "Escolher a que tenant aceder, quando o utilizador pertence a mais do que um.", quemUsa: "Utilizador com vários vínculos (Membership)." },
    es: { titulo: "Seleccionar empresa", objetivo: "Elegir a qué tenant acceder, cuando el usuario pertenece a más de uno.", quemUsa: "Usuario con múltiples vínculos (Membership)." },
    fr: { titulo: "Sélectionner l'entreprise", objetivo: "Choisir à quel tenant accéder, lorsque l'utilisateur appartient à plusieurs.", quemUsa: "Utilisateur ayant plusieurs rattachements (Membership)." },
  },
  "checkin.overview": {
    "pt-BR": {
      titulo: "Check-in / Embarque",
      objetivo: "Validar a credencial (QR/token) de um passageiro e confirmar check-in ou embarque no ponto de encontro.",
      quemUsa: "Equipe de operação (quem tem checkin.execute/boarding.execute).",
      campos: "Token da credencial (colado ou lido do link).",
      estados: "AGENDADO → CHECKIN_REALIZADO → EMBARCADO, com NO_SHOW/CANCELADO como desvios.",
      acoes: "Confirmar check-in; confirmar embarque (exige check-in feito antes); marcar no-show manualmente.",
      avisos: "O token nunca é um ID interno (Booking/Traveler) — é um código aleatório opaco, sem sentido fora do sistema. Um token expirado, revogado ou de outro tenant é sempre rejeitado.",
    },
    en: {
      titulo: "Check-in / Boarding",
      objetivo: "Validate a passenger's credential (QR/token) and confirm check-in or boarding at the meeting point.",
      quemUsa: "Operations staff (whoever has checkin.execute/boarding.execute).",
      campos: "Credential token (pasted or read from the link).",
      estados: "SCHEDULED → CHECKED_IN → BOARDED, with NO_SHOW/CANCELLED as deviations.",
      acoes: "Confirm check-in; confirm boarding (requires check-in first); manually mark a no-show.",
      avisos: "The token is never an internal ID (Booking/Traveler) — it's an opaque random code, meaningless outside the system. An expired, revoked, or other-tenant token is always rejected.",
    },
    "pt-PT": {
      titulo: "Check-in / Embarque",
      objetivo: "Validar a credencial (QR/token) de um passageiro e confirmar check-in ou embarque no ponto de encontro.",
      quemUsa: "Equipa de operação.",
      acoes: "Confirmar check-in; confirmar embarque; marcar no-show manualmente.",
    },
    es: {
      titulo: "Check-in / Embarque",
      objetivo: "Validar la credencial (QR/token) de un pasajero y confirmar el check-in o embarque en el punto de encuentro.",
      quemUsa: "Equipo de operaciones.",
      acoes: "Confirmar check-in; confirmar embarque; marcar no-show manualmente.",
    },
    fr: {
      titulo: "Enregistrement / Embarquement",
      objetivo: "Valider l'identifiant (QR/jeton) d'un passager et confirmer l'enregistrement ou l'embarquement au point de rendez-vous.",
      quemUsa: "Équipe opérationnelle.",
      acoes: "Confirmer l'enregistrement ; confirmer l'embarquement ; marquer une absence manuellement.",
    },
  },
  "parceiros.overview": {
    "pt-BR": {
      titulo: "Parceiros",
      objetivo: "Cadastro de parceiros externos que indicam clientes e recebem comissão por isso.",
      quemUsa: "Vendas, Administrador.",
      campos: "Nome, código (identificador público do parceiro), tipo, contato, e-mail.",
      acoes: "Cadastrar; ativar/desativar.",
      avisos: "Parceiro é sempre externo — distinto do vendedor interno responsável por uma reserva.",
    },
    en: {
      titulo: "Partners",
      objetivo: "Registry of external partners who refer customers and earn a commission for it.",
      quemUsa: "Sales, Administrator.",
      campos: "Name, code (partner's public identifier), type, contact, email.",
      acoes: "Register; activate/deactivate.",
      avisos: "A Partner is always external — distinct from the internal salesperson responsible for a booking.",
    },
    "pt-PT": { titulo: "Parceiros", objetivo: "Cadastro de parceiros externos que indicam clientes e recebem comissão por isso.", quemUsa: "Vendas, Administrador.", acoes: "Cadastrar; ativar/desativar." },
    es: { titulo: "Socios", objetivo: "Registro de socios externos que refieren clientes y reciben una comisión por ello.", quemUsa: "Ventas, Administrador.", acoes: "Registrar; activar/desactivar." },
    fr: { titulo: "Partenaires", objetivo: "Registre des partenaires externes qui recommandent des clients et perçoivent une commission.", quemUsa: "Ventes, Administrateur.", acoes: "Enregistrer ; activer/désactiver." },
  },
  "premiacoes.overview": {
    "pt-BR": {
      titulo: "Premiações",
      objetivo: "Campanhas de premiação por meta de vendas para parceiros — distintas de comissão por venda individual.",
      quemUsa: "Administrador.",
      campos: "Nome, meta (nº de vendas), valor, moeda, janela de datas.",
      acoes: "Criar campanha.",
      avisos: "Pagamento de premiação sempre passa por aprovação (Gate financeiro), igual comissão.",
    },
    en: {
      titulo: "Rewards",
      objetivo: "Sales-target reward campaigns for partners — distinct from per-sale commission.",
      quemUsa: "Administrator.",
      campos: "Name, target (number of sales), amount, currency, date window.",
      acoes: "Create a campaign.",
      avisos: "Reward payouts always go through approval (a financial Gate), same as commissions.",
    },
    "pt-PT": { titulo: "Premiações", objetivo: "Campanhas de premiação por meta de vendas para parceiros.", quemUsa: "Administrador.", acoes: "Criar campanha." },
    es: { titulo: "Premios", objetivo: "Campañas de premios por meta de ventas para socios.", quemUsa: "Administrador.", acoes: "Crear campaña." },
    fr: { titulo: "Récompenses", objetivo: "Campagnes de récompenses par objectif de ventes pour les partenaires.", quemUsa: "Administrateur.", acoes: "Créer une campagne." },
  },
  "ouvidoria.list": {
    "pt-BR": {
      titulo: "Ouvidoria",
      objetivo: "Central de reclamações, elogios, dúvidas e solicitações pós-venda — distinta do Inbox (atendimento em tempo real) e do funil de Leads.",
      quemUsa: "Atendimento, Administrador.",
      campos: "Protocolo (gerado automaticamente), categoria, prioridade, status.",
      estados: "ABERTO → EM_ANDAMENTO → RESOLVIDO → FECHADO (reabertura permitida a partir de RESOLVIDO).",
      acoes: "Abrir um ticket; filtrar por status; clicar para abrir o detalhe.",
    },
    en: {
      titulo: "Support / Ombudsman",
      objetivo: "Hub for complaints, compliments, questions and post-sale requests — distinct from the Inbox (real-time support) and the Leads funnel.",
      quemUsa: "Support, Administrator.",
      campos: "Protocol (auto-generated), category, priority, status.",
      estados: "OPEN → IN_PROGRESS → RESOLVED → CLOSED (reopening allowed from RESOLVED).",
      acoes: "Open a ticket; filter by status; click to open the detail page.",
    },
    "pt-PT": { titulo: "Ouvidoria", objetivo: "Central de reclamações, elogios, dúvidas e solicitações pós-venda.", quemUsa: "Atendimento, Administrador.", acoes: "Abrir um ticket; filtrar por estado." },
    es: { titulo: "Atención al cliente", objetivo: "Centro de quejas, elogios, dudas y solicitudes post-venta.", quemUsa: "Atención al cliente, Administrador.", acoes: "Abrir un ticket; filtrar por estado." },
    fr: { titulo: "Médiation client", objetivo: "Centre des réclamations, compliments, questions et demandes après-vente.", quemUsa: "Support, Administrateur.", acoes: "Ouvrir un ticket ; filtrer par statut." },
  },
  "ouvidoria.detail": {
    "pt-BR": {
      titulo: "Detalhe do ticket",
      objetivo: "Acompanhar e responder um ticket de ouvidoria — thread de mensagens, mudança de status, avaliação do cliente ao final.",
      quemUsa: "Atendimento, Administrador.",
      campos: "Mensagens (cliente/equipe), resolução, nota de avaliação (1-5) e comentário quando fechado.",
      acoes: "Responder; mudar status; ver avaliação quando disponível.",
    },
    en: {
      titulo: "Ticket detail",
      objetivo: "Follow up and reply to a support ticket — message thread, status change, customer rating at the end.",
      quemUsa: "Support, Administrator.",
      campos: "Messages (customer/team), resolution, rating (1-5) and comment once closed.",
      acoes: "Reply; change status; view the rating when available.",
    },
    "pt-PT": {
      titulo: "Detalhe do ticket",
      objetivo: "Acompanhar e responder a um ticket de apoio ao cliente — fio de mensagens, mudança de estado, avaliação do cliente no final.",
      quemUsa: "Atendimento, Administrador.",
      campos: "Mensagens (cliente/equipa), resolução, nota de avaliação (1-5) e comentário quando fechado.",
      acoes: "Responder; mudar o estado; ver a avaliação quando disponível.",
    },
    es: {
      titulo: "Detalle del ticket",
      objetivo: "Seguir y responder un ticket de atención al cliente — hilo de mensajes, cambio de estado, valoración del cliente al final.",
      quemUsa: "Atención al cliente, Administrador.",
      campos: "Mensajes (cliente/equipo), resolución, nota de valoración (1-5) y comentario al cerrar.",
      acoes: "Responder; cambiar el estado; ver la valoración cuando esté disponible.",
    },
    fr: {
      titulo: "Détail du ticket",
      objetivo: "Suivre et répondre à un ticket de médiation client — fil de messages, changement de statut, évaluation du client à la fin.",
      quemUsa: "Support, Administrateur.",
      campos: "Messages (client/équipe), résolution, note d'évaluation (1-5) et commentaire à la clôture.",
      acoes: "Répondre ; changer le statut ; voir l'évaluation lorsqu'elle est disponible.",
    },
  },
  "operacoes.overview": {
    "pt-BR": {
      titulo: "Central de Operações",
      objetivo: "Visão consolidada, só leitura, de todas as viagens confirmadas ou em andamento: crew, veículo, check-in/embarque, mapa ao vivo e alertas operacionais.",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Nenhum formulário — a gestão de cada grupo continua na página da viagem.",
      estados: "Alertas: sem rastreamento ativo, check-in não iniciado a menos de 24h da partida, capacidade lotada.",
      acoes: "Clicar no roteiro leva para a página da viagem, onde a gestão de fato acontece.",
      avisos: "Alertas são calculados a partir de dado real (nunca um valor fixo) — se nada estiver errado, nenhum alerta aparece.",
    },
    en: {
      titulo: "Operations Center",
      objetivo: "Consolidated, read-only view of every confirmed or in-progress trip: crew, vehicle, check-in/boarding, live map and operational alerts.",
      quemUsa: "Sales, Support, Administrator.",
      campos: "No forms here — managing a group still happens on the trip page.",
      estados: "Alerts: no active tracking, check-in not started within 24h of departure, vehicle at capacity.",
      acoes: "Click the itinerary name to go to the trip page, where the actual management happens.",
      avisos: "Alerts are computed from real data (never a hardcoded value) — if nothing is wrong, no alert appears.",
    },
    "pt-PT": {
      titulo: "Central de Operações",
      objetivo: "Visão consolidada, só de leitura, de todas as viagens confirmadas ou em curso: equipa, veículo, check-in/embarque, mapa em tempo real e alertas operacionais.",
      quemUsa: "Vendas, Atendimento, Administrador.",
      acoes: "Clicar no roteiro leva à página da viagem, onde a gestão acontece de facto.",
    },
    es: {
      titulo: "Central de Operaciones",
      objetivo: "Vista consolidada, solo lectura, de todos los viajes confirmados o en curso: equipo, vehículo, check-in/embarque, mapa en vivo y alertas operativas.",
      quemUsa: "Ventas, Atención al cliente, Administrador.",
      acoes: "Hacer clic en el itinerario lleva a la página del viaje, donde ocurre la gestión real.",
    },
    fr: {
      titulo: "Centre d'opérations",
      objetivo: "Vue consolidée, lecture seule, de tous les voyages confirmés ou en cours : équipe, véhicule, check-in/embarquement, carte en direct et alertes opérationnelles.",
      quemUsa: "Ventes, Support, Administrateur.",
      acoes: "Cliquer sur l'itinéraire ouvre la page du voyage, où se passe la gestion réelle.",
    },
  },
  "notificacoes.overview": {
    "pt-BR": {
      titulo: "Notificações",
      objetivo: "Avisos sobre eventos relevantes das suas próprias reservas e tarefas — sempre pessoais, nunca uma central de notificação de outra pessoa.",
      quemUsa: "Todos os papéis — cada um só vê as próprias notificações.",
      campos: "Nenhum formulário — só leitura e marcação de lida/não lida.",
      estados: "Nova (não lida) ou lida. O número ao lado do link no menu mostra quantas ainda não foram lidas.",
      acoes: "Marcar uma notificação como lida, ou todas de uma vez.",
      avisos: "Cobertura de eventos cresce aos poucos — hoje, pagamento recebido numa reserva sua. Mais eventos (proposta aceita, documento pendente, viagem confirmada) serão adicionados progressivamente.",
    },
    en: {
      titulo: "Notifications",
      objetivo: "Alerts about relevant events on your own bookings and tasks — always personal, never someone else's notification center.",
      quemUsa: "Every role — each person only sees their own notifications.",
      campos: "No forms — read-only, plus marking as read/unread.",
      estados: "New (unread) or read. The number next to the menu link shows how many are still unread.",
      acoes: "Mark one notification as read, or all of them at once.",
      avisos: "Event coverage grows over time — today, payment received on one of your bookings. More events (proposal accepted, pending document, confirmed trip) will be added progressively.",
    },
    "pt-PT": {
      titulo: "Notificações",
      objetivo: "Avisos sobre eventos relevantes das suas próprias reservas e tarefas — sempre pessoais, nunca uma central de notificação de outra pessoa.",
      quemUsa: "Todos os papéis — cada um só vê as próprias notificações.",
      acoes: "Marcar uma notificação como lida, ou todas de uma vez.",
    },
    es: {
      titulo: "Notificaciones",
      objetivo: "Avisos sobre eventos relevantes de tus propias reservas y tareas — siempre personales, nunca una central de notificaciones de otra persona.",
      quemUsa: "Todos los roles — cada uno ve solo sus propias notificaciones.",
      acoes: "Marcar una notificación como leída, o todas a la vez.",
    },
    fr: {
      titulo: "Notifications",
      objetivo: "Alertes sur les événements pertinents de vos propres réservations et tâches — toujours personnelles, jamais un centre de notifications d'un tiers.",
      quemUsa: "Tous les rôles — chacun ne voit que ses propres notifications.",
      acoes: "Marquer une notification comme lue, ou toutes en une fois.",
    },
  },
  "avaliacoes.overview": {
    "pt-BR": {
      titulo: "Avaliações",
      objetivo: "Avaliações (nota de 1 a 5) e depoimentos que os próprios clientes registram depois que a viagem termina — nunca preenchidas pela equipe em nome do cliente.",
      quemUsa: "Vendas, Atendimento, Administrador.",
      campos: "Nenhum formulário — a avaliação é feita pelo cliente, na própria área dele (link 'Minha viagem').",
      estados: "Consentiu depoimento / sem consentimento — se o cliente autorizou usar o comentário como depoimento público. Publicado / não publicado — decisão separada, sempre de um humano da equipe.",
      acoes: "Publicar ou despublicar um depoimento (só quando o cliente já consentiu).",
      avisos: "Publicar nunca é automático, mesmo com consentimento — sempre exige um clique de alguém da equipe. Uma avaliação só existe depois que a reserva chega ao status Concluída.",
    },
    en: {
      titulo: "Reviews",
      objetivo: "Ratings (1 to 5) and testimonials that clients themselves submit after the trip ends — never filled in by staff on the client's behalf.",
      quemUsa: "Sales, Support, Administrator.",
      campos: "No forms here — the review is submitted by the client, on their own area ('My trip' link).",
      estados: "Consented to testimonial / no consent — whether the client authorized using their comment as a public testimonial. Published / unpublished — a separate decision, always made by a staff member.",
      acoes: "Publish or unpublish a testimonial (only once the client has already consented).",
      avisos: "Publishing is never automatic, even with consent — it always requires a staff click. A review only exists once the booking reaches the Completed status.",
    },
    "pt-PT": {
      titulo: "Avaliações",
      objetivo: "Avaliações (nota de 1 a 5) e depoimentos que os próprios clientes registam depois de a viagem terminar — nunca preenchidas pela equipa em nome do cliente.",
      quemUsa: "Vendas, Atendimento, Administrador.",
      acoes: "Publicar ou despublicar um depoimento (só quando o cliente já consentiu).",
    },
    es: {
      titulo: "Evaluaciones",
      objetivo: "Calificaciones (de 1 a 5) y testimonios que los propios clientes registran después de que termina el viaje — nunca completados por el equipo en nombre del cliente.",
      quemUsa: "Ventas, Atención al cliente, Administrador.",
      acoes: "Publicar o despublicar un testimonio (solo cuando el cliente ya haya dado su consentimiento).",
    },
    fr: {
      titulo: "Avis",
      objetivo: "Notes (de 1 à 5) et témoignages que les clients soumettent eux-mêmes après la fin du voyage — jamais remplis par l'équipe au nom du client.",
      quemUsa: "Ventes, Support, Administrateur.",
      acoes: "Publier ou dépublier un témoignage (seulement une fois le consentement du client déjà obtenu).",
    },
  },
  "public.home": {
    "pt-BR": {
      titulo: "Site público",
      objetivo: "Página inicial pública da agência: roteiros, inspirações, saídas disponíveis e o formulário de orçamento — quem visita não tem conta nem sessão.",
      quemUsa: "Visitante anônimo do site.",
      acoes: "Pedir um orçamento pelo formulário 'Por onde começamos?', falar por WhatsApp/e-mail, ou navegar pelas outras páginas do site (Universo amazigh, Sabores do Marrocos).",
    },
    en: {
      titulo: "Public site",
      objetivo: "The agency's public homepage: itineraries, inspirations, available departures and the quote request form — visitors have no account or session.",
      quemUsa: "Anonymous site visitor.",
      acoes: "Request a quote via the 'Where shall we start?' form, reach out by WhatsApp/email, or browse the site's other pages (Amazigh universe, Flavours of Morocco).",
    },
    "pt-PT": {
      titulo: "Site público",
      objetivo: "Página inicial pública da agência: roteiros, inspirações, saídas disponíveis e o formulário de orçamento — quem visita não tem conta nem sessão.",
      quemUsa: "Visitante anónimo do site.",
      acoes: "Pedir um orçamento pelo formulário 'Por onde começamos?', contactar por WhatsApp/e-mail, ou navegar pelas outras páginas do site.",
    },
    es: {
      titulo: "Sitio público",
      objetivo: "Página de inicio pública de la agencia: itinerarios, inspiraciones, salidas disponibles y el formulario de presupuesto — quien visita no tiene cuenta ni sesión.",
      quemUsa: "Visitante anónimo del sitio.",
      acoes: "Pedir un presupuesto con el formulario '¿Por dónde empezamos?', contactar por WhatsApp/correo, o navegar por las demás páginas del sitio.",
    },
    fr: {
      titulo: "Site public",
      objetivo: "Page d'accueil publique de l'agence : circuits, inspirations, départs disponibles et le formulaire de devis — les visiteurs n'ont ni compte ni session.",
      quemUsa: "Visiteur anonyme du site.",
      acoes: "Demander un devis via le formulaire « Par où commencer ? », contacter par WhatsApp/e-mail, ou parcourir les autres pages du site.",
    },
  },
  "public.amazigh": {
    "pt-BR": {
      titulo: "Universo amazigh",
      objetivo: "Página editorial sobre a cultura e a história amazigh (povos, língua, escrita Tifinagh, celebrações) — conteúdo de leitura, não um formulário.",
      quemUsa: "Visitante anônimo do site.",
      acoes: "Ler as histórias e seguir os links de fontes acadêmicas/institucionais citadas, ou pedir um orçamento no formulário ao final da página.",
    },
    en: {
      titulo: "Amazigh universe",
      objetivo: "Editorial page about Amazigh culture and history (peoples, language, Tifinagh script, celebrations) — reading content, not a form.",
      quemUsa: "Anonymous site visitor.",
      acoes: "Read the stories and follow the cited academic/institutional source links, or request a quote in the form at the bottom of the page.",
    },
    "pt-PT": {
      titulo: "Universo amazigh",
      objetivo: "Página editorial sobre a cultura e a história amazigh (povos, língua, escrita Tifinagh, celebrações) — conteúdo de leitura, não um formulário.",
      quemUsa: "Visitante anónimo do site.",
      acoes: "Ler as histórias e seguir as fontes académicas/institucionais citadas, ou pedir um orçamento no formulário no final da página.",
    },
    es: {
      titulo: "Universo amazigh",
      objetivo: "Página editorial sobre la cultura y la historia amazigh (pueblos, lengua, escritura tifinagh, celebraciones) — contenido de lectura, no un formulario.",
      quemUsa: "Visitante anónimo del sitio.",
      acoes: "Leer las historias y seguir los enlaces de fuentes académicas/institucionales citadas, o pedir un presupuesto en el formulario al final de la página.",
    },
    fr: {
      titulo: "Univers amazigh",
      objetivo: "Page éditoriale sur la culture et l'histoire amazighes (peuples, langue, écriture tifinagh, célébrations) — contenu de lecture, pas un formulaire.",
      quemUsa: "Visiteur anonyme du site.",
      acoes: "Lire les récits et suivre les liens vers les sources académiques/institutionnelles citées, ou demander un devis dans le formulaire en bas de page.",
    },
  },
  "public.sabores": {
    "pt-BR": {
      titulo: "Sabores do Marrocos",
      objetivo: "Página editorial sobre a gastronomia marroquina: pratos, receitas e curiosidades — conteúdo de leitura, não um formulário.",
      quemUsa: "Visitante anônimo do site.",
      acoes: "Ler os pratos e receitas, abrir 'Fontes e leituras' de cada seção, ou pedir um orçamento no formulário ao final da página.",
    },
    en: {
      titulo: "Flavours of Morocco",
      objetivo: "Editorial page about Moroccan gastronomy: dishes, recipes and trivia — reading content, not a form.",
      quemUsa: "Anonymous site visitor.",
      acoes: "Read the dishes and recipes, open 'Sources and further reading' on each section, or request a quote in the form at the bottom of the page.",
    },
    "pt-PT": {
      titulo: "Sabores de Marrocos",
      objetivo: "Página editorial sobre a gastronomia marroquina: pratos, receitas e curiosidades — conteúdo de leitura, não um formulário.",
      quemUsa: "Visitante anónimo do site.",
      acoes: "Ler os pratos e receitas, abrir 'Fontes e leituras' de cada secção, ou pedir um orçamento no formulário no final da página.",
    },
    es: {
      titulo: "Sabores de Marruecos",
      objetivo: "Página editorial sobre la gastronomía marroquí: platos, recetas y curiosidades — contenido de lectura, no un formulario.",
      quemUsa: "Visitante anónimo del sitio.",
      acoes: "Leer los platos y recetas, abrir 'Fuentes y lecturas' de cada sección, o pedir un presupuesto en el formulario al final de la página.",
    },
    fr: {
      titulo: "Saveurs du Maroc",
      objetivo: "Page éditoriale sur la gastronomie marocaine : plats, recettes et anecdotes — contenu de lecture, pas un formulaire.",
      quemUsa: "Visiteur anonyme du site.",
      acoes: "Lire les plats et recettes, ouvrir « Sources et lectures » de chaque section, ou demander un devis dans le formulaire en bas de page.",
    },
  },
};
